### ISSUE TITLE
remove the outside circle

### ISSUE THREAD

**Issue by hejian41** [Simon-Leonard/FlexDotPlot#1]
Hi, 
Your FlexDotPlot is very convenient for dot plot data from Seurat. Is there any parameter that removes the outside circles?

Regards,
Jian
![image](https://user-images.githubusercontent.com/38309419/91813038-a194f500-ec64-11ea-8cd0-fdbe293fcba6.png)

**Comment by Simon-Leonard** [comment]
Hi Jian,

You can add the parameter "display_max_sizes = FALSE" in the dot_plot function and it should do the trick !

Bests
Simon
