### ISSUE TITLE
how to increase the size of the color key and the pct exp legend of the chart?

### ISSUE THREAD

**Issue by TorteloteLab** [Simon-Leonard/FlexDotPlot#3]
First off, 
thank you for this nice chart.
I plot the following chart, but I could not change the size of the color key and the pct. exp legend. 
I tried to use ggplot themes, but it does not appear to work either.
Is there a way to do it?
I thank you in advance.

![image](https://user-images.githubusercontent.com/58445209/99313559-60ed5680-2825-11eb-80a5-ab836b773ad3.png)

**Comment by Simon-Leonard** [comment]
Hi,

Maybe you can try to use the grid.arrange function with the grobs from the dotplot output and different widths/heigths : 

First, you run the dotplot function like you did :
`dot_plot_output = dot_plot( ... )`

You have access to actual widths and heigths with :
```
as.vector(dot_plot_output$plot$widths)
as.vector(dot_plot_output$plot$heights)
```

If you want to change them, define new widths/heights :
```
# Widths of : y-dendrogramm, y-axis labels (left), dotplot, y-axis labels (right), Size legend, Shape legend, Color legend
widths=c(0,3,20,0,0,3,3)

# Heights of : x-dendrogramm, x-axis labels (top), dotplot, x-axis labels (bottom)
heigths=c(0,0,20,3)
```


And run grid.arrange function with the new widths/heigths : 

```
#Do not change the layout matrix
layout_matrix=rbind(c(NA,NA,1,NA,NA,NA,NA),
                    c(NA,NA,2,NA,NA,NA,NA),
                    c(3,4,5,6,7,8,9),
                    c(NA,NA,10,NA,NA,NA,NA))

grid.arrange(grobs=dot_plot_output$plot$grobs, layout_matrix=layout_matrix, widths=widths, heigths=heigths)
```

Maybe it would be easier to improve the dotplot width/height than decrease legend sizes.

Simon

**Comment by TorteloteLab** [comment]
Thank you very much. 
Great help!
