### ISSUE TITLE
How to use unique color for dots in each row?

### ISSUE THREAD

**Issue by JING202** [Simon-Leonard/FlexDotPlot#4]
Hi,

I want to draw a dotplot as below.
Is this possible to define color for dots in each row using FlexDotPlot?  Thanks.
![1638693027356](https://user-images.githubusercontent.com/92959962/144739429-bf29e76e-460a-4f3e-8825-72067dfc8f5b.jpg)

**Comment by Simon-Leonard** [comment]
Hi,

Yes you can do that by using the name of the column used for the y axis in the col_var parameter.
col_var=2 (or col_var=1 if you set the transpose parameter to true) also works as the column used for y-axis should be in the second position !

Simon

**Comment by JING202** [comment]
Hi Simon,

Thanks for your reply. 
Previously I used "avg.exp.scaled" in the col_var parameter. As you suggested, I changed it to the name of column. It works.
But there is no gradient color for each row, only show dot size based on "Percent expressed". 

Can I also show the gradient color based on "avg.exp.scaled"? Thanks.

**Comment by Simon-Leonard** [comment]
Oh, this is more complicated than I expected ! 
I'm afraid that there is no simple solution to do that. I think I would process all the lines separately with a different color scale and merge the resulting dot plots with arrangeGrob commands or with a graphics tool like Inkscape.
Simon

**Comment by JING202** [comment]
Thanks. I would try your suggestions.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
