### ISSUE TITLE
Warning message: In PCA(FAMD_final_input, graph = F, ncp = min(dim(FAMD_final_input)) -  :   Missing values are imputed by the mean of the variable: you should use the imputePCA function of the missMDA package

### ISSUE THREAD

**Issue by denvercal1234GitHub** [Simon-Leonard/FlexDotPlot#6]
Hi there, 

Thanks for the package. 

I encountered the below Warning when trying to run on my data frame from `FindAllMarkers` output data frame as input. Would you mind giving me some pointers to address it? 

Thank you again. 

```
FlexDotPlot::dot_plot(data.to.plot = as.data.frame(allClusters_signif_posneg_DEG_FCsorted_top5perCluster), size_var = "pct.1",shape.scale = 9, shape_var= ifelse(allClusters_signif_posneg_DEG_FCsorted_top5perCluster$avg_log2FC>0, "Up","Down"), col_var = "avg_log2FC", dend_x_var = NULL,dend_y_var = c("pct.1","avg_log2FC"), dist_method="euclidean", hclust_method="ward.D", size_legend="% positive cells", shape_legend="Up/Down", col_legend="Avg log2FC")
```
My data frame: 
<img width="554" alt="Screenshot 2023-12-07 at 11 56 44" src="https://github.com/Simon-Leonard/FlexDotPlot/assets/62179082/ad8666f5-303f-44a9-bc91-ac9c340a4e7d">

```
Warning message: In PCA(FAMD_final_input, graph = F, ncp = min(dim(FAMD_final_input)) -  :   Missing values are imputed by the mean of the variable: you should use the imputePCA function of the missMDA package
```

**Comment by Simon-Leonard** [comment]
Hi,

I suppose that you checked that you don't have any missing value in your input table. 
Can you send me a data frame input to reproduce the warning ?

Best, 
Simon
